# Generated by Django 3.1 on 2022-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0003_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='place_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
