# Generated by Django 3.1 on 2022-07-09 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0004_status_place_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(default='NoCategory', max_length=200),
        ),
    ]
