# Generated by Django 3.1 on 2022-07-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0006_place_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
