# Generated by Django 3.1 on 2022-07-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line_bot', '0008_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
